HTML:
- any: ['**/**/*.html']
EJS:
- any: ['**/**/*.ejs']
CSS:
- any: ['**/**/*.css']
JavaScript:
- any: ['**/**/*.js']
  all: ['!functions/index.js']
images:
- any: ['public/images/**/*.*']
workflows:
- any: ['.github/workflows/*']
front-end:
- any: ['public/**/*']
back-end:
- any: ['functions/**/*']
dependencies:
- any: ['functions/package.json', 'functions/package-lock.json']
documentation:
- any: ['**/*.md']
